  # download Lemontree.Automation on a runner and setup the license
    name: GetLTA
    uses: LieberLieber/setup-LemonTree.Automation@v6
    id: GetLTA
    with:
      License: ${{inputs.License}} 
  #ExeLocation &"${{steps.GetLTA.outputs.LemonTreeAutomationExecutable}}"
  
  # first simple use of LemonTree.Automation
  - name: ConsistencyCheck
    run: |
      &"${{steps.GetLTA.outputs.LemonTreeAutomationExecutable}}" ConsistencyCheck --Model "model.qeax"
