# action.yaml
name: 'Get LemonTreeAutomation'
uses: LieberLieber/setup-LemonTree.Automation@v1.0
description: 'This action downloads LieberLieber LemonTree.Automation for Sparx Systems Enterprise Architect on a build runner!'
inputs:
  License:
    description: 'A string containing the license information'
    required: true
    default: ''
outputs:
  LemonTreeAutomationExecutable:
    description: 'Path to the Executable'
    value: "${{steps.DownloadLTA.outputs.LemonTreeAutomationExecutable}}"
runs:
  using: 'composite'
  steps:
    - id: DownloadLTA
      run: "& $env:GITHUB_ACTION_PATH/getLTA.ps1 -RunnerOs '${{runner.os}}'-License 'LICENSE lieber lemontree3.automation 2099.12 31-dec-2025 single
  hostid=ANY share=h:32 issuer="LieberLieber Software GmbH" 
  customer="Sparx Systems India/ Prolaborate" issued=16-jan-2025
  type=demo _ck=f81ff6543a sig="60P0450KBH0GEFBGYNWA291FX05N22TFGN81DU
  022HPPD5TJ8M5N652BSHTHT567N4NE65SFQC"'"
      shell: pwsh
