name: 'Get LemonTreeAutomation'
description: 'This action downloads LieberLieber LemonTree.Automation for Sparx Systems Enterprise Architect on a build runner!'
inputs:
  License:
    description: 'A string containing the license information'
    required: true
outputs:
  LemonTreeAutomationExecutable:
    description: 'Path to the Executable'
    value: "${{ steps.DownloadLTA.outputs.LemonTreeAutomationExecutable }}"
runs:
  using: 'composite'
  steps:
    - id: DownloadLTA
      shell: pwsh
      run: |
        param (
          [string]$License
        )
        Write-Host "Using License: $License"
        & $env:GITHUB_ACTION_PATH/getLTA.ps1 -RunnerOs $env:RUNNER_OS -License ${{ secrets.LEMON_TREE_LICENSE }}
