name: Setup LemonTree Automation

on:
  push:
    branches:
      - main

jobs:
  setup-lemontree:
    runs-on: windows-latest

    steps:
      # Checkout the repository to access files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Use the published LieberLieber action
      - name: Get LemonTreeAutomation
        uses: LieberLieber/setup-LemonTree.Automation@v1.0
        with:
          License: ${{ secrets.LEMONTREE_LICENSE }}  # Pass the secret here
