name: lemon license PowerShell Script

on:
  push:
    branches:
      - main

jobs:
  test-script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run getLTA.ps1 script
      shell: pwsh  # Use PowerShell Core (pwsh) on the runner
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope Process -Force
        echo "${{ secrets.LICENSE_KEY }}" | base64 --decode > license.txt
        & .\LTA\LemonTree.Automation.exe  consistencycheck --model .\Balu.eapx --license '${{secrets.LICENSE_KEY}}'
     
          
