 # download Lemontree.Automation on a runner and setup the license
name: setup-LemonTree.Automation Sample Workflow
on:
    push:
     
jobs:
    setup-LemonTree: 
      defaults:
        run:
          shell: pwsh
      runs-on: [windows-latest] 
      timeout-minutes: 15
      steps:  
        - uses: actions/checkout@v4
          with:
            lfs: true
            fetch-depth: 0
            
        # first simple use of LemonTree.Automation
        - name: ConsistencyCheck
          run: |
            &".github/LTA/LemonTree.Automation.exe" ConsistencyCheck --Model "model.qeax"
