name: lemon PowerShell Script

on:
  push:
    branches:
      - main

jobs:
  test-script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run getLTA.ps1 script
      shell: pwsh  # Use PowerShell Core (pwsh) on the runner
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope Process -Force
        & "$env:GITHUB_WORKSPACE\.github\LTA\LemonTree.Automation.exe" ConsistencyCheck --Model "model_name"
     
          
