name: Test PowerShell Script

on:
  push:
    branches:
      - main

jobs:
  test-script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    - name: Run getLTA.ps1 script
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope Process -Force
        .\getLTA.ps1 -License "my-license-key" -RunnerOs "Windows"
