name: Windows Test

on:
  push:

env:
  ModelName: DemoModel
  ModelExtension: eapx
  ACTION_PATH: ${{ vars.ACTION_PATH }}

jobs:
  ConsistencyCheck:
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      
      # Create the license file from the secret
      - name: Set License File
        run: |
          echo "${{ secrets.bala }}" > license.lic
      
      - name: Verify License File
        run: |
          if (Test-Path license.lic) {
            Write-Host "License file created successfully."
          } else {
            Write-Host "License file creation failed."
          }
        shell: pwsh
      
      # Run LemonTree.Automation using the license
      - name: ConsistencyCheck
        run: |
          &"$Env:ACTION_PATH\LemonTreeAutomation.exe" ConsistencyCheck --Model ${{env.ModelName}}.${{env.ModelExtension}} --License license.lic
        shell: pwsh
