name: lemon license PowerShell Script

on:
  push:
    branches:
      - main

jobs:
  test-script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run getLTA.ps1 script
      shell: pwsh  # Use PowerShell Core (pwsh) on the runner
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope Process -Force
        & .\LTA\LemonTree.Automation.exe  consistencycheck --model .\Balu.eapx -license 'LICENSE lieber lemontree3.automation 2099.12 31-dec-2025 single hostid=ANY share=h:32 issuer="LieberLieber Software GmbH" customer="Sparx Systems India/ Prolaborate" issued=16-jan-2025 type=demo _ck=f81ff6543a sig="60P0450KBH0GEFBGYNWA291FX05N22TFGN81DU 022HPPD5TJ8M5N652BSHTHT567N4NE65SFQC"'
     
          
